#!/usr/bin/env bash
# declaration of my function
myfunc () {
	arr=(www lb-01 web-01 web-02)
	command_line=$(grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	if [ ! "$2" ]
	then
		for i in "${arr[@]}";do
			echo "The subdomain $i is a  $(dig "$i.$1") | $command_line | $(awk '{print $1 " record and points to " $2}')" 
		done
	fi
	if [  "$2" ]
		then
			echo "The subdomain $2 is a $(dig "$2.$1") | $command_line | $(awk '{print $1 " record and points to "  $2 }')"
	fi
}

# called the function
myfunc "$1" "$2"
