#!/usr/bin/env bash
# declaration of my function
myfunc () {
	command_line=$(dig "$2.$1 | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $command_line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to "  $3 }'
}

# called the function
arr=(www lb-01 web-01 web-02)
if [ ! "$2" ]
then
	for i in "${arr[@]}";do
		myfunc "$1" "$i"
	done
else
	myfunc "$1" "$2"
fi
