#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server
if ['$#' -lt 3];then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
# SINON
scp -i ${BASH_ARGV[3]} ${BASH_ARGV[0]} ${BASH_ARGV[2]}@${BASH_ARGV[1]}:~/
