#!/usr/bin/env bash
# Redirection
CONFIGFILE=/etc/nginx/sites-available/default
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sed -i "53i\ \n\tlocation /redirect_me {\n\t\treturn 301 https://www.linkedin.com/in/wasscodeur/; \n\t}" $CONFIGFILE
service nginx start
