#!/usr/bin/env bash
# Redirection
sed -i '/http {/a\\tserver {\n\t\tlisten 80;\n\t\tserver_name 18.210.17.157;\n\t\tlocation /redirect_me {\n\t\t\treturn 301 https://www.alxafrica.com;\n\t\t}\n\t}' /etc/nginx/nginx.conf