#!/usr/bin/env bash
# Custum ERROR FILE
apt-get update -y
apt-get install nginx ufw -y
ufw allow 'Nginx HTTP'
CONFIGFILE="/etc/nginx/sites-available/default"
ERRORFILE="/var/www/html/custom_404.html"
INDEXFILE="/var/www/html/index.html"
echo -e "Ceci n'est pas une page\n\n" > $ERRORFILE
echo "Hello World!" > $INDEXFILE
sed -i "53i\ \n\terror_page 404 /custom_404.html; \n\tlocation = /custom_404.html {\n\t\tinternal; \n\t}" $CONFIGFILE
sed -i "53i\  \n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n\t}" $CONFIGFILE
service nginx start
