#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it
current_date=$(date +%d-%m-%Y)
dump_file="backup.sql"
archive_file="$current_date.tar.gz"
db_user="root"
db_pwrd="$1"
mysqldump -u "$db_user" -p"$db_pwrd" --all-databases > "$dump_file"
tar -cvzf "$archive_file" "$dump_file"
echo "$dump_file"
