#!/usr/bin/env bash
# delete de sybolic link
rm /etc/nginx/sites-enabled/default
# create a new symbolic link
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
