#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Get the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f '7-highlander')

# Send the TERM signal to the 4-to_infinity_and_beyond process using its PID
kill -TERM $pid