#!/bin/bash

# Get the PID of the 7-highlander process
pid=$(pgrep -f 7-highlander)

# Check if the process was found
if [ -z "$pid" ]; then
    echo "7-highlander process not found"
    exit 1
else
    echo "Killed"
    kill $pid
    exit 0
fi

