#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely
# With a sleep 2 between each iteration
# "I am invincible!!" upon receiving a SIGTERM signal

# Function to handle the SIGTERM signal
function terminate {
  echo "I am invincible!! ./7-highlander"
  exit 0
}

# Trap the SIGTERM signal
trap terminate SIGTERM

while :; do
  echo "To infinity and beyond"
  sleep 2
done
