#!/usr/bin/env bash
# This script kills the 7-highlander process
# And displays "I am invincible!!" upon receiving a SIGTERM signal

# Get the PID of the 7-highlander process
pid=$(pgrep -f '7-highlander')

# Kill the 7-highlander process using its PID
kill $pid
