#!/usr/bin/env bash
# This script is displaying numbers 1 to 20, with special messages for 4, 8, and 17
i=1
while ((i<= 20))
do
    echo "$i"
    
    case $i in
    4)
        echo "bad luck from China"
    ;;
    8)
        echo "bad luck from Japan"
    ;;
    17)
        echo "bad luck from Italy"
    ;;
    esac
    
    ((i++))
done
