#!/usr/bin/env bash
#script that configures an Ubuntu server
cp /etc/hosts ~/hosts.new
echo '127.0.0.2        localhost' > ~/hosts.new
echo '$a 8.8.8.8       facebook'>> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
