#!/usr/bin/env bash
# change nginx's user to nginx
chmod 644 /etc/nginx/nginx.conf
sed -i '/user/s/.*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
