#!/usr/bin/env bash
# change nginx's user to nginx
chmod 644 /etc/nginx/nginx.conf
sed -i '/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart
