#!/usr/bin/env bash
chmod 644 /etc/nginx/nginx.conf
sed -i '/user/s/.*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx restart
